language: go

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=f97333d5fd390f3f77c129767cf8970cd288bf201bddee48e52197c86c7ce9c9

stages:
  - test
  - deploy

go:
  - 1.13.x

sudo: required
dist: trusty

services:
  - docker

before_install:
  - go get -u golang.org/x/lint/golint
  - curl -L https://github.com/commander-cli/commander/releases/download/v2.1.0/commander-linux-amd64 -o ~/bin/commander
  - chmod +x ~/bin/commander

jobs:
  include:
  - name: Go lint
    stage: test
    script: make lint

  - name: macOS Unit
    os: osx
    script:
      - make test

  - name: macOS integration
    os: osx
    script:
      - curl -L https://github.com/commander-cli/commander/releases/download/v2.1.0/commander-darwin-amd64 -o ~/bin/commander
      - chmod +x ~/bin/commander
      - make integration-unix

  - name: windows Unit
    os: windows
    before_install:
      - choco install make
    script:
      - make test

  - name: windows integration
    os: windows
    before_install:
      - choco install make
      - choco install curl
      - curl -L https://github.com/commander-cli/commander/releases/download/v2.1.0/commander-windows-amd64 -o C:\Windows\system32\commander.exe
    script:
      - make integration-windows

  - name: Unit tests
    script:
      - make test

  - name: Unit test all
    before_script:
      - curl https://s3.amazonaws.com/codeclimate/test-reporter/test-reporter-0.6.3-linux-amd64 --output test-reporter
      - chmod +x test-reporter
      - ./test-reporter before-build
    script:
      - make test-coverage-all
    after_script:
      - ./test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

  - name: Integration test
    script:
      - docker pull docker.io/library/alpine:3.11.3
      - make integration-linux

  - stage: deploy
    name: "Deployment"
    if: tag IS present
    script: make release
    deploy:
      provider: releases
      overwrite: true
      api_key: $GITHUB_TOKEN
      file:
        - release/commander-linux-amd64
        - release/commander-linux-arm
        - release/commander-linux-386
        - release/commander-darwin-amd64
        - release/commander-darwin-386
        - release/commander-windows-amd64.exe
        - release/commander-windows-386.exe
      skip_cleanup: true
      on:
        repo: commander-cli/commander
        tags: true
