language: go

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=4015795135868ee4781bd8cad1d345c20e7d0c2ef6ad5b0f08ccb13da24e66a1

stages:
  - test

go:
  - 1.11.x

sudo: required
dist: trusty

services:
  - docker

before_install:
  - go get -u golang.org/x/lint/golint

jobs:
  include:
  - name: Go lint
    stage: test
    script: make lint

  - name: Unit tests
    before_script:
      - curl https://s3.amazonaws.com/codeclimate/test-reporter/test-reporter-0.6.3-linux-amd64 --output test-reporter
      - chmod +x test-reporter
      - ./test-reporter before-build
    script:
      - make test-coverage
    after_script:
      - ./test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

  - name: Integration test
    script: make test-integration
