config:
  env:
    KEY: value
    ANOTHER: global
    COMMANDER_FROM_SHELL: ${COMMANDER_FROM_SHELL}
tests:
  should print global env value:
    command: echo $KEY
    stdout: value
    exit-code: 0

  should print local env value:
    command: echo $KEY $ANOTHER
    config:
      env:
        KEY: local
    stdout: local global
    exit-code: 0

  should execute in given dir:
    command: pwd
    config:
      dir: /tmp
    stdout: /tmp
    exit-code: 0

  it should work with timeout:
    command: echo hello
    config:
      timeout: 100ms
    exit-code: 0

  should print env var from shell:
    command: echo read ${COMMANDER_FROM_SHELL} $KEY
    stdout: read from_shell value
    exit-code: 0