config:
  env:
    KEY: value
    ANOTHER: global
tests:
  should print global env value:
    command: echo %KEY%
    stdout: value
    exit-code: 0

  should print local env value:
    command: echo %KEY% %ANOTHER%
    config:
      env:
        KEY: local
    stdout: local global
    exit-code: 0

  should execute in given dir:
    command: dir
    config:
      dir: C:\
    stdout:
      contains:
        - "C:"
        - "Program Files"
        - "Users"
    exit-code: 0

  should work with timeout:
    command: echo hello
    config:
      timeout: 100
    exit-code: 0